/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package futbolturnuvasi;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nihat
 */
public class AnaMenu extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenu
     */
    Turnuva turnuva;

    public AnaMenu() throws IOException {
        initComponents();
        turnuva = new Turnuva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DosyaOkuButon = new javax.swing.JButton();
        TurnuvaBaslatButon = new javax.swing.JButton();
        KadroGosterButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        DosyaOkuButon.setBackground(new java.awt.Color(0, 204, 0));
        DosyaOkuButon.setForeground(new java.awt.Color(0, 0, 0));
        DosyaOkuButon.setText("Dosya Oku");
        DosyaOkuButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosyaOkuButonActionPerformed(evt);
            }
        });

        TurnuvaBaslatButon.setBackground(new java.awt.Color(0, 204, 0));
        TurnuvaBaslatButon.setForeground(new java.awt.Color(0, 0, 0));
        TurnuvaBaslatButon.setText("Turnuvayı Başlat");
        TurnuvaBaslatButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurnuvaBaslatButonActionPerformed(evt);
            }
        });

        KadroGosterButon.setBackground(new java.awt.Color(0, 204, 0));
        KadroGosterButon.setForeground(new java.awt.Color(0, 0, 0));
        KadroGosterButon.setText("Kadro Göster");
        KadroGosterButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KadroGosterButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KadroGosterButon, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DosyaOkuButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TurnuvaBaslatButon, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(DosyaOkuButon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TurnuvaBaslatButon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KadroGosterButon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DosyaOkuButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosyaOkuButonActionPerformed
        // TODO add your handling code here:
        DosyaOku dosyaOku = new DosyaOku();
        dosyaOku.setVisible(true);
        this.setVisible(false);
        dosyaOku.turnuva = turnuva;
    }//GEN-LAST:event_DosyaOkuButonActionPerformed

    private void TurnuvaBaslatButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurnuvaBaslatButonActionPerformed
        // TODO add your handling code here:
        TurnuvaSonuc turnuvaSonuc = new TurnuvaSonuc();
        turnuvaSonuc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TurnuvaBaslatButonActionPerformed

    private void KadroGosterButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KadroGosterButonActionPerformed
        // TODO add your handling code here:
        KadroGoster takim = null;
        try {
            takim = new KadroGoster();
            takim.turnuva = turnuva;
        } catch (IOException ex) {
            Logger.getLogger(AnaMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        takim.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KadroGosterButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AnaMenu().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AnaMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DosyaOkuButon;
    private javax.swing.JButton KadroGosterButon;
    private javax.swing.JButton TurnuvaBaslatButon;
    // End of variables declaration//GEN-END:variables
}
